name: Unit Tests - Windows

on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.3.1' # minimum requirement
          - '1'
        julia-arch: [x64, x86]
        os: [windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
